proxy = "wss://localhost:7081/ws"
name = "display01"
player = "http://localhost:7081/roundaudio"
kiosk = true

[clienttls]
type = "dev"
[clienttls.dev]
usesystempool = false
interval = "10h"


[log]
level = "debug"
